image: python:3.8

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip install twine
    - echo "[distutils]" > ~/.pypirc
    - echo "index-servers = pypi" >> ~/.pypirc
    - echo "[pypi]" >> ~/.pypirc
    - echo "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
    - echo "username: __token__" >> ~/.pypirc
    - echo "password: $pyfbs_token" >> ~/.pypirc
    - python setup.py sdist bdist_wheel
    - twine upload --skip-existing --verbose --config-file ~/.pypirc dist/*
  only:
    - tags