stages:
  - publish

publish:
  stage: publish
  image: python:3.8
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ -u __token__ -p $PYPI_TOKEN dist/*
  only:
    - tags