dist: xenial

branches:
  only:
  - travis_ci

os:
  - linux

language: python
python:
  - "3.8"
  
before_install:
  - set -x
  - sudo apt update && sudo apt install python-qt4 libgl1-mesa-glx
  - sudo apt-get install -y xvfb
  - export DISPLAY=:99.0
  - export PYVISTA_OFF_SCREEN=True
  - which Xvfb
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
  - set +x
  
  - pip install pytest  
  - pip install pytest-cov
  - pip install pytest-qt
  
  
install:
  - pip install .
  
  - pip install pyvista
  - pip install pyvistaqt
    
  - pip install qtpy>=1.9.0
  - pip install scooby>=0.5.1
  - pip install PyQt5==5.11.3

jobs:
  include:
    - stage: "Test"     
      name: "Compile"    
      script:
        - pytest -v ./tests/test_plotting.py

#    - stage: "Documentation" 
#      name: "Documentation"     
#      script: echo Documentation

#    - stage: "Deploy to PyPi"
#      name: "Deploy"
#      script: echo Deploy
  
notifications:
  email: false