[tox]
envlist = py38

[testenv]
deps =
    #-r requirements-dev.txt
	
commands =
	
	pip install pytest  
    pip install pytest-cov
    pip install pytest-qt
	
	pip install pyvista
    pip install pyvistaqt
    
    pip install qtpy>=1.9.0
    pip install scooby>=0.5.1
    pip install PyQt5==5.11.3
    pip install nbconvert
    pip install jupyterlab
    pytest -v ./tests/test_plotting.py
    pytest -v ./tests/build_examples.py