[tox]
envlist = py{38,39}
skipsdist = True

[testenv]
passenv = 

deps =
    -r requirements_dev.txt
	codecov
	
commands =
	codecov
	pip install -e .
	pip install pywin32==306
	
    pytest -v --cov-report term --cov=app/test/
	pytest -v ./tests/build_examples.py

